name: Build book PDF
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile book PDF
        uses: dante-ev/latex-action@master
        with:
          working_directory: book
          root_file: calcnotes.tex
      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: book
          path: book/calcnotes.pdf
